steps:
- id: build
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '$_IMAGE', '.']
- id: push
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', '$_IMAGE']
- id: 'deploy-1'
  name: 'gcr.io/cloud-builders/gcloud:$_CLOUDSDK_VERSION'
  waitFor: ['push']
  script: |
    #!/bin/bash
    gcloud run deploy example \
      --image $_IMAGE \
      --region $_REGION           
  env:
    - '_IMAGE=$_IMAGE'
    - '_REGION=$_REGION'
    - 'PROJECT_ID=$PROJECT_ID'
substitutions:  
  _REGION: 'us-central1'
  _IMAGE: '${_REGION}-docker.pkg.dev/${PROJECT_ID}/default/example'
  _CLOUDSDK_VERSION: 'latest'
options:
  dynamic_substitutions: true
