apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator
  namespace: shop-demo
spec:
  template:
    spec:
      containers:
      - name: main
        env:
        - name: USERS
          value: "1000"
