steps:
- id: "Build workload image"
  waitFor: ['-'] 
  name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '-t', '${_REPO}/${_IMAGE}',
          '${_SRC}'         
         ]

- id: "Push to AR"
  name: 'gcr.io/cloud-builders/docker'
  waitFor: ['Build workload image']  
  args: ['push', '${_REPO}/${_IMAGE}']

timeout: 300s
substitutions:
  _REPO: 'us-central1-docker.pkg.dev/mslarkin-ext/mslarkin-utils'
  _SRC: './go-flexible-workload'
  _IMAGE: go-flexible-workload

options:
    dynamic_substitutions: true
    substitution_option: 'ALLOW_LOOSE'
    logging: CLOUD_LOGGING_ONLY 
    # logging: GCS_ONLY 
