steps:
- id: build
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '$_IMAGE', '.']
- id: push
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', '$_IMAGE']
- id: 'deploy'
  name: 'gcr.io/cloud-builders/gcloud:$_CLOUDSDK_VERSION'
  script: |
    #!/bin/bash
    gcloud run deploy $_SERVICE \
      --image $_IMAGE \
      --region $_REGION \
      --use-http2      
  env:
    - '_IMAGE=$_IMAGE'
    - '_REGION=$_REGION'
    - '_SERVICE=$_SERVICE'
    - 'PROJECT_ID=$PROJECT_ID'

substitutions:  
  _REGION: 'us-central1'
  _SERVICE: 'collector'
  _IMAGE: '${_REGION}-docker.pkg.dev/${PROJECT_ID}/default/${_SERVICE}'
  _CLOUDSDK_VERSION: 'latest'
options:
  dynamic_substitutions: true
