#!/bin/bash

#####
# Add this command to the end of .profile or .bash_profile
# source ~/msl-playground/config/mslarkin_bash_profile
# Profile only runs on login
#####

echo "Running mslarkin_bash_profile (login)"

####
# Update gcloud
####
gcloud components update -q

npm install -g @google/gemini-cli &> /dev/null
