#!/bin/bash

#####
# Add this command to the end of .profile or .bash_profile 
# source ~/msl-playground/config/mslarkin_bash_profile
# Profile only runs on login
#####

echo "Running mslarkin_bash_profile (login)"

###
# Set up Git
###
git config --global user.email "matthewlarkin@google.com"
git config --global user.name "Matt Larkin"

################
# Install Docker
################
if [ ! -f /usr/bin/docker ]; then
    echo "Docker not found, installing..."
    bash <(curl -s https://get.docker.com)
fi
################
# Install Hey
################
if [ ! -d "$HOME/local_tools" ]; then
    mkdir -p ~/local_tools
fi
if [ ! -f ~/local_tools/hey_linux_amd64 ]; then
    echo "Hey not found, installing..."
    curl https://hey-release.s3.us-east-2.amazonaws.com/hey_linux_amd64 --output ~/local_tools/hey_linux_amd64
    chmod +x ~/local_tools/hey_linux_amd64
fi
alias hey='~/local_tools/hey_linux_amd64'

################
# Install Node Version Manager (NVM)
################
if [ ! -d "$HOME/.config/nvm" ]; then
    echo "NVM not found, installing..."
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
    nvm install --lts
fi