#!/bin/sh
######
# Add /home/matthewlarkin/msl-playground/config/mslarkin_cloudshell_customize_environment to ~/.customize_environment
#
# Logs for this script in /var/log/customize_environment
# Will touch /google/devshell/customize_environment_done when complete
######

# apt-get update

######
# Install pyenv dependencies
######
# apt-get install -y libncurses5-dev libncursesw5-dev tk-dev python-openssl