#!/bin/bash

#####
# Add this command to the end of .bashrc
# source ~/msl-playground/config/mslarkin_bash_config
# .bashrc runs every time the terminal is opened
#####

echo "Running mslarkin_bash_config (new shell)"

###
# Set up Git
###
git config --global user.email "matthewlarkin@google.com"
git config --global user.name "Matt Larkin"
git config --global credential.helper store

# Set up gcloud
if gcloud config configurations describe mslarkin-ext &> /dev/null; then
  gcloud config configurations activate mslarkin-ext
else
  echo "Creating new gcloud configuration: mslarkin-ext"
  gcloud config configurations create mslarkin-ext
  gcloud config configurations activate mslarkin-ext
  gcloud config set project mslarkin-ext
  gcloud config set run/region us-west1
  gcloud config set account matthewlarkin@google.com
  gcloud config set builds/region us-west1
  gcloud config set ai/region us-west1
  gcloud config set compute/region us-west1
  gcloud config set compute/zone us-west1-b
fi

# Set up Kubectl autocomplete
source <(kubectl completion bash) # set up autocomplete in bash into the current shell, bash-completion package should be installed first.

################
# Set up useful aliases
################
alias gcurl='curl --header "Authorization: Bearer $(gcloud auth application-default print-access-token)"'
# alias gcurl_id='curl --header "Authorization: Bearer $(gcloud auth print-identity-token)"'
alias refreshauth='GOPROXY=proxy.golang.org go run github.com/GoogleCloudPlatform/artifact-registry-go-tools/cmd/auth@v0.1.0 refresh'
alias pip-remove-all='pip freeze | xargs pip uninstall -y'
alias rw-mslarkin='rw mslarkin.c.googlers.com'
# alias tf='terraform'
# ln ~/mslarkin/config/GEMINI.md ~/.gemini/GEMINI.md
alias gemini-dl="npx https://github.com/google-gemini/gemini-cli"
alias gemini-update="npm install -g @google/gemini-cli"
alias mcp-inspect='npx @modelcontextprotocol/inspector'
alias gcc-ext='gcloud config configurations activate mslarkin-ext'
alias gcc-demo='gcloud config configurations activate mslarkin-demo'

# export CLOUDSDK_AUTH_ACCESS_TOKEN="$(gcloud auth application-default print-access-token)"
# export CLOUDSDK_AUTH_ID_TOKEN="$(gcloud auth print-identity-token)"

export PATH=$PATH:/home/matthewlarkin/local_tools
