#!/bin/bash

#####
# Add this command to the end of .bashrc
# source ~/msl-playground/config/mslarkin_bash_config
# .bashrc runs every time the terminal is opened
#####

echo "Running mslarkin_bash_config (new shell)"

###
# Set up Git
###
if [ ! -d "$HOME/google-cloud-sdk" ]; then
  sudo apt install git -y
fi
git config --global user.email "matthewlarkin@google.com"
git config --global user.name "Matt Larkin"
git config --global credential.helper store

################
# Install gcloud cli
################
if [ ! -d "$HOME/google-cloud-sdk" ]; then
    curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-linux-x86_64.tar.gz
    tar -xf google-cloud-cli-linux-x86_64.tar.gz

    # Add to PATH
    ./google-cloud-sdk/install.sh -q --rc-path $HOME/.bashrc

    # Cleanup
    rm google-cloud-cli-linux-x86_64.tar.gz
    sudo reboot
fi

################
# Install Docker
################
if [ ! -f /usr/bin/docker ]; then
    echo "Docker not found, installing..."

    ## External
    # bash <(curl -s https://get.docker.com)

    # gLinux
    sudo glinux-add-repo docker-ce-"$(lsb_release -cs)"
    sudo apt update
    sudo apt install docker-ce

    sudo systemctl stop docker
    sudo ip link set docker0 down
    sudo ip link del docker0

    # * move Docker's storage location for more space.
    # * avoid conflicts between the Docker bridge and Corp IPs
    # * turn on the debug mode, if you don't want that you could set that to false
    sudo tee /etc/docker/daemon.json <<EOF
    {
        "data-root": "/usr/local/google/docker",
        "bip": "192.168.9.1/24",
        "default-address-pools": [
            {
            "base": "192.168.11.0/22",
            "size": 24
            }
        ],
        "storage-driver": "overlay2",
        "debug": true,
        "registry-mirrors": ["https://mirror.gcr.io"]
    }
EOF

    sudo systemctl start docker
    sudo systemctl enable docker

    ## Setup GCR credential helper
    gcloud auth configure-docker -q

    ## Add external repos
    ## Support pushing and pulling "us-docker.pkg.dev" images
    gcloud auth configure-docker -q us-docker.pkg.dev
fi

################
# Install Terraform
################
if [ ! -f "$HOME/bin/terraform" ]; then
export TERRAFORM_VERSION=1.13.0
cd ~
mkdir bin
curl -O "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip"
unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip
mv terraform bin/
rm terraform_${TERRAFORM_VERSION}_linux_amd64.zip
fi

################
# Install Hey
################
if [ ! -d "$HOME/local_tools" ]; then
    mkdir -p ~/local_tools
fi
if [ ! -f ~/local_tools/hey_linux_amd64 ]; then
    echo "Hey not found, installing..."
    curl https://hey-release.s3.us-east-2.amazonaws.com/hey_linux_amd64 --output ~/local_tools/hey_linux_amd64
    chmod +x ~/local_tools/hey_linux_amd64
fi
alias hey='~/local_tools/hey_linux_amd64'

################
# Install Node Version Manager (NVM) & Node.js
################
if [ ! -d "$HOME/.config/nvm" ]; then
    echo "NVM not found, installing..."
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
    nvm install --lts
fi


# npm install -g @google/gemini-cli
# ln ~/mslarkin/config/GEMINI.md ~/.gemini/GEMINI.md
npm update -g @google/gemini-cli

################
# Set up GCP Project environment
################
# gcloud config set core/user_output_enabled False &> /dev/null
# if [[ "$(gcloud config list project | grep project)" == *"(unset)"* ]]; then
#   gcloud config set project mslarkin-ext
# fi
# gcloud config set run/region us-west1
# gcloud config set account matthewlarkin@google.com
# gcloud config set builds/region us-west1
# gcloud config set ai/region us-west1

## These require the project to be set
# gcloud config set compute/region us-west1
# gcloud config set compute/zone us-west1-b

# gcloud config unset core/user_output_enabled

# gcloud config list

# Set up Go tools
# export PATH=$PATH:/usr/local/go/bin:/home/matthewlarkin/go/bin:/home/matthewlarkin/local_tools

################
# Set up useful aliases
################
alias gcurl='curl --header "Authorization: Bearer $(gcloud auth print-access-token)"'
# alias gcurl_id='curl --header "Authorization: Bearer $(gcloud auth print-identity-token)"'
alias refreshauth='GOPROXY=proxy.golang.org go run github.com/GoogleCloudPlatform/artifact-registry-go-tools/cmd/auth@v0.1.0 refresh'
alias pip-remove-all='pip freeze | xargs pip uninstall -y'
alias tf='terraform'
################
# Set up Kubectl
################
if [ ! -f "/usr/bin/kubectl" ]; then
  sudo apt install kubectl
  gcloud components install gke-gcloud-auth-plugin

  # Set up auth for each cluster
  # mslarkin-autopilot
  gcloud container clusters get-credentials mslarkin-autopilot \
    --location=us-west1 --project mslarkin-tf
fi
# Set up Kubectl autocomplete
source <(kubectl completion bash) # set up autocomplete in bash into the current shell, bash-completion package should be installed first.
source <(helm completion bash)


# export CLOUDSDK_AUTH_ACCESS_TOKEN="$(gcloud auth print-access-token)"
# export CLOUDSDK_AUTH_ID_TOKEN="$(gcloud auth print-identity-token)"

export PATH=$PATH:/home/matthewlarkin/local_tools
