steps:
- name: gcr.io/cloud-builders/gcloud
  args:
  - 'artifacts'
  - 'go'
  - 'upload'
  - '--project=$PROJECT_ID'
  - '--source=${_SRC}'
  - '--location=${_LOCATION}'
  - '--repository=${_REPO}'
  - '--module-path=${_MODULE_PATH}'
  - '--version=${_VERSION}'

timeout: 300s
substitutions:
  _LOCATION: 'us-central1'
  _MODULE_PATH: 'github.com/mlarkin00/mslarkin/go-mslarkin-utils/${_MODULE_NAME}'
  _REPO: 'https://us-central1-go.pkg.dev/mslarkin-ext/mslarkin-go-repo'
  _SRC: './go-mslarkin-utils/${_MODULE_NAME}'
  _VERSION: 'v1.0.0'

options:
    dynamic_substitutions: true
    substitution_option: 'ALLOW_LOOSE'
    logging: CLOUD_LOGGING_ONLY 
    # logging: GCS_ONLY 
