steps:
- id: "Build workload image"
  waitFor: ['-'] 
  name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '-t', '${_REPO}/${_IMAGE}',
          '${_SRC}'         
         ]

- id: "Push to AR"
  name: 'gcr.io/cloud-builders/docker'
  waitFor: ['Build workload image']  
  args: ['push', '${_REPO}/${_IMAGE}']

timeout: 300s
substitutions:
  _REPO: 'us-west1-docker.pkg.dev/mslarkin-ext/mslarkin-utils'
  _SRC: './loadgen-utils/loadgenConfig'
  _IMAGE: loadgen-config

options:
    dynamicSubstitutions: true
    substitutionOption: 'ALLOW_LOOSE'
    logging: CLOUD_LOGGING_ONLY 
    # logging: GCS_ONLY 
